"""Added new fields to user table

Revision ID: 0de77b29f731
Revises: 7392fbc36f06
Create Date: 2023-01-03 17:32:29.474076

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0de77b29f731"
down_revision = "7392fbc36f06"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("first_name", sa.String(length=200), nullable=False)
        )
        batch_op.add_column(
            sa.Column("last_name", sa.String(length=200), nullable=False)
        )
        batch_op.add_column(
            sa.Column("username", sa.String(length=200), nullable=False)
        )
        batch_op.create_unique_constraint(None, ["username"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("username")
        batch_op.drop_column("last_name")
        batch_op.drop_column("first_name")

    # ### end Alembic commands ###
